# Generated by Django 5.2 on 2025-04-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveloa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelrating',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='hotelrating',
            name='user',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='attraction',
            name='rating_count',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='created_at',
        ),
        migrations.AddField(
            model_name='attraction',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='attraction',
            name='entry_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='attraction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='AttractionRating',
        ),
        migrations.DeleteModel(
            name='HotelRating',
        ),
    ]
