# Generated by Django 5.2 on 2025-04-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveloa', '0002_remove_hotelrating_hotel_remove_hotelrating_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
