# Generated by Django 4.2.20 on 2025-04-10 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveloa', '0003_hotel_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='elo_rating',
            field=models.FloatField(default=1500),
        ),
    ]
