# Generated by Django 5.2 on 2025-04-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveloa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attraction',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
